---
- name: Deploy Scientific Calculator Docker Container
  hosts: local
  # This requires the 'jenkins' user to have NOPASSWD access in /etc/sudoers to run Docker commands as root
  become: yes

  vars:
    # IMPORTANT: The image name MUST match the one defined in your Jenkinsfile
    app_image: "aayushbhargav57/scientific-calculator:latest"
    container_name: "scientific_calculator_app"

  tasks:
    - name: Ensure Python Docker module is installed
      pip:
        name: docker
        state: present

    - name: Stop and remove existing container (if running)
      # Use the fully qualified collection name for the docker_container module
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Pull the latest Docker image from Docker Hub
      community.docker.docker_image:
        name: "{{ app_image }}"
        source: pull

    - name: Run the new container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ app_image }}"
        state: started
        # Detach the container so the Jenkins job can finish
        detach: true
        # The app is command-line only; it will run the entrypoint (Main class)
        # and exit after execution unless in an interactive environment.
        # For continuous running CLI, you'd use a loop in the Entrypoint/CMD,
        # but for this assignment, a started container is sufficient.
